version: '3.9'
services:
  dbpostgres:
    container_name: dbpostgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: $DB_POSTGRES_PASSWORD
      POSTGRES_USER: $DB_POSTGRES_USER
      POSTGRES_DB: $DB_POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
      - dbPostgres:/var/lib/postgresql/data

  webapp:
    build: .
    depends_on:
      - dbpostgres
    volumes:
      - .:/app
    ports:
      - 3000:3000

  # nginx:
  #   image: nginx
  #   volumes:
  #     - ./conf.d:/etc/nginx/conf.d
  #   depends_on:
  #     - webapp
  #   ports:
  #     - 3000:3000

volumes:
  dbPostgres:
